### ISSUE TITLE
[feature-request] Almost full and almost empty signals

### ISSUE THREAD

**Issue by renzenicolai** [ThotIP/async_fifo#1]
Hello Damien Pretet,

I've been using your fifo in one of my projects for the last two weeks and so far it has worked flawlessly. Thank you for your contribution to the open source world!

There is however a feature that your fifo doesn't have and which I would really like to see: almost full and almost empty signals, to know a clock-tick in advance if the fifo is going to be full or empty.

Would it be possible for you to add those kinds of signals?

Thank you!

Greetings,
Renze Nicolai

**Comment by dpretet** [comment]
Hello Nicola,

Good to see you use this IP, specially if easy to integrate in your project :D

Yes sure I can add it. I will add a parameter to let you configure the time the new flags will raise. By default, you’ll know it one cycle early. The s it good to you?

**Comment by renzenicolai** [comment]
Yes, that would be perfect! Thank you for your quick response!

**Comment by renzenicolai** [comment]
Hello,

Were you able to add the new flags? I look forward to continuing my project.

Greetings,
Renze

**Comment by dpretet** [comment]
Hello,  

No sorry I didn’t get time last days to work on it. I will during the weekend for sure!  

Cheers,  
Damien


Le 16 mars 2018 à 15:36:33, Renze Nicolai (notifications@github.com(mailto:notifications@github.com)) a écrit:

**Comment by renzenicolai** [comment]
No problem!
In the meantime I've "solved" it by using two fifos in series: One feeds into the other. That way I can have the extra full/empty signals I need without changes to the fifo itself.

**Comment by dpretet** [comment]
Nice trick :D Can you explain me your project? Would love to know how my dev can help.  


Le 16 mars 2018 à 19:04:48, Renze Nicolai (notifications@github.com(mailto:notifications@github.com)) a écrit:

**Comment by dpretet** [comment]
I pushed on branch issue01 a first implementation. I'm writing more tests to ensure it works well, but if you want to give a try before an official tag you are welcome.

**Comment by dpretet** [comment]
Sounds to be alive. Pushed into v1.1.0 officially
