### ISSUE TITLE
Address width parameter on sync_x blocks not passed through from toplevel

### ISSUE THREAD

**Issue by juliusbaxter** [ThotIP/async_fifo#2]
Hi,

I've just tried using your block on the issue01 branch and have noticed that the address width parameter inside the sync_r2w and sync_w2r blocks is not specified on the their instance in async_fifo.v, meaning if you change the parameter on the instance of an async_fifo instance then it doesn't propagate down and causes the block to issue a lot of Xes.

It's also inconsistently named in those sync modules versus the others (ADDRSIZE vs ASIZE).

Thanks.

**Comment by dpretet** [comment]
Hi Julius. Thanks for the PR I’ll take a look during the weekend and merge the pull request.

**Comment by dpretet** [comment]
I rename ADDRSIZE for ASIZE everywhere, as well DATASIZE with DSIZE. Thanks for your code review. Pushed in v1.1.0
